import * as fs from 'fs';
import * as path from 'path';
import { Task } from '../models/task';
import { ExecutionResult } from '../models/execution';
import { logger } from './logger';

/**
 * 进度摘要生成器
 *
 * 在每次任务执行完成后生成进度摘要，供下一个 session 参考
 */
export class ProgressSummaryGenerator {
  private defaultMaxLength = 2000;

  constructor() {
    // 空构造函数，可在需要时扩展
  }

  /**
   * 生成进度摘要内容
   */
  async generate(
    task: Task,
    executionResult: ExecutionResult
  ): Promise<string> {
    const { status, output, duration } = executionResult;
    const maxLength = task.execution.progressConfig?.maxLength || this.defaultMaxLength;

    // 限制输出长度
    const outputSnippet = output
      ? output.substring(0, maxLength) + (output.length > maxLength ? '\n...(truncated)' : '')
      : 'No output';

    // 获取 git 当前状态（如果可用）
    let gitState = '';
    try {
      const { execSync } = await import('child_process');
      const stdout = execSync('git status --short', {
        cwd: task.execution.workingDir || '.',
        encoding: 'utf-8',
      });

      if (stdout && stdout.trim()) {
        gitState = `\n\n### Git Status\n\`\`\`\n${stdout.trim()}\n\`\`\``;
      }
    } catch {
      // git 不可用，忽略
      logger.debug('Git not available in working directory', {
        workingDir: task.execution.workingDir,
      });
    }

    // 生成摘要
    const summary = `## Session Progress Summary

**Task**: ${task.name}
**Group**: ${task.execution.sessionGroup || 'N/A'}
**Status**: ${status}
**Executed at**: ${new Date().toISOString()}
**Duration**: ${duration}ms

### Output
\`\`\`
${outputSnippet}
\`\`\`
${gitState}

### Next Steps
<!-- 由后续 Claude Code session 自动填写下一步 -->

---
*Generated by Cadence at ${new Date().toISOString()}*
`;

    return summary;
  }

  /**
   * 保存进度摘要到文件
   */
  async save(
    task: Task,
    summary: string
  ): Promise<string> {
    // 确定输出路径
    const outputPath = task.execution.progressConfig?.outputPath
      || path.join(task.execution.workingDir || '.', `.claude`, `progress-${task.execution.sessionGroup || 'default'}.md`);

    const dir = path.dirname(outputPath);

    // 确保目录存在
    fs.mkdirSync(dir, { recursive: true });

    // 写入文件
    fs.writeFileSync(outputPath, summary);

    logger.info('Progress summary saved', {
      task: task.id,
      group: task.execution.sessionGroup,
      path: outputPath,
      length: summary.length,
    });

    return outputPath;
  }

  /**
   * 检查是否启用进度摘要
   */
  isEnabled(task: Task): boolean {
    return task.execution.progressConfig?.enabled !== false;
  }
}
